name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci || npm i
      - name: Verify project structure
        run: |
          test -f public/index.html
          test -f src/app.js
          test -f tests/basic.test.js
          echo "Estructura OK"
      - name: Run tests
        run: npm test --silent